<?
$PERM["lichnyy-kabinet-pokupatelya"]["6"]="R";
$PERM["lichnyy-kabinet-pokupatelya"]["*"]="D";
$PERM["lichnyy-kabinet-prodavtsa"]["7"]="R";
$PERM["lichnyy-kabinet-prodavtsa"]["*"]="D";
$PERM["bitrix"]["8"]="D";
$PERM["obyavleniya"]["8"]="X";
$PERM["o-servise"]["8"]="X";
$PERM["news"]["8"]="X";
$PERM["news"]["5"]="W";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["index.php"]["5"]="W";
$PERM["/"]["*"]="R";
?>